[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "INFO-5940"
version = "1.0.0"
description = "RAG Chatbot"
authors = ["Ayham Boucher <private>"]

[tool.poetry.dependencies]
python = "^3.11"

pymupdf = "1.24.11"  # 确保和 Dockerfile 一致！
chromadb = "0.5.13"  # 确保和 Dockerfile 一致！
streamlit = "^1.20"  # 确保 Streamlit 可用！

openai = "^1.14"
tiktoken = "^0.7.0"
langchain = "^0.2.15"
langchain-openai = "^0.1.23"
langchain-community = "^0.2.15"
langchain_core = "^0.2.15"
faiss-cpu = "^1.7.4"
pandas = "^2"
pydantic = "^2"

[tool.poetry.group.dev.dependencies]
cfn_flip = "*"
cfn-lint = "*"
ipykernel = "*"
openpyxl = "*"
beautifulsoup4 = "*"
pyarrow = "*"
